<?xml version="1.0" encoding="UTF-8" ?>
<Package name="OpenRobertaClient" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="icon" src="icon.png" />
        <File name="main" src="scripts/main.py" />
        <File name="__init__" src="scripts/stk/__init__.py" />
        <File name="events" src="scripts/stk/events.py" />
        <File name="logging" src="scripts/stk/logging.py" />
        <File name="runner" src="scripts/stk/runner.py" />
        <File name="services" src="scripts/stk/services.py" />
        <File name="libffi-56d8fba3.so.6.0" src="scripts/.libs_cffi_backend/libffi-56d8fba3.so.6.0.4" />
        <File name="SSL" src="scripts/OpenSSL/SSL.py" />
        <File name="__init__" src="scripts/OpenSSL/__init__.py" />
        <File name="_util" src="scripts/OpenSSL/_util.py" />
        <File name="crypto" src="scripts/OpenSSL/crypto.py" />
        <File name="debug" src="scripts/OpenSSL/debug.py" />
        <File name="rand" src="scripts/OpenSSL/rand.py" />
        <File name="tsafe" src="scripts/OpenSSL/tsafe.py" />
        <File name="version" src="scripts/OpenSSL/version.py" />
        <File name="__init__" src="scripts/__init__.py" />
        <File name="_cffi_backend" src="scripts/_cffi_backend.so" />
        <File name="__init__" src="scripts/asn1crypto/__init__.py" />
        <File name="_elliptic_curve" src="scripts/asn1crypto/_elliptic_curve.py" />
        <File name="_errors" src="scripts/asn1crypto/_errors.py" />
        <File name="_ffi" src="scripts/asn1crypto/_ffi.py" />
        <File name="_inet" src="scripts/asn1crypto/_inet.py" />
        <File name="_int" src="scripts/asn1crypto/_int.py" />
        <File name="_iri" src="scripts/asn1crypto/_iri.py" />
        <File name="_ordereddict" src="scripts/asn1crypto/_ordereddict.py" />
        <File name="__init__" src="scripts/asn1crypto/_perf/__init__.py" />
        <File name="_big_num_ctypes" src="scripts/asn1crypto/_perf/_big_num_ctypes.py" />
        <File name="_teletex_codec" src="scripts/asn1crypto/_teletex_codec.py" />
        <File name="_types" src="scripts/asn1crypto/_types.py" />
        <File name="algos" src="scripts/asn1crypto/algos.py" />
        <File name="cms" src="scripts/asn1crypto/cms.py" />
        <File name="core" src="scripts/asn1crypto/core.py" />
        <File name="crl" src="scripts/asn1crypto/crl.py" />
        <File name="csr" src="scripts/asn1crypto/csr.py" />
        <File name="keys" src="scripts/asn1crypto/keys.py" />
        <File name="ocsp" src="scripts/asn1crypto/ocsp.py" />
        <File name="parser" src="scripts/asn1crypto/parser.py" />
        <File name="pdf" src="scripts/asn1crypto/pdf.py" />
        <File name="pem" src="scripts/asn1crypto/pem.py" />
        <File name="pkcs12" src="scripts/asn1crypto/pkcs12.py" />
        <File name="tsp" src="scripts/asn1crypto/tsp.py" />
        <File name="util" src="scripts/asn1crypto/util.py" />
        <File name="version" src="scripts/asn1crypto/version.py" />
        <File name="x509" src="scripts/asn1crypto/x509.py" />
        <File name="__init__" src="scripts/backports/__init__.py" />
        <File name="__init__" src="scripts/backports/ssl/__init__.py" />
        <File name="core" src="scripts/backports/ssl/core.py" />
        <File name="monkey" src="scripts/backports/ssl/monkey.py" />
        <File name="subject_alt_name" src="scripts/backports/ssl/subject_alt_name.py" />
        <File name="__init__" src="scripts/certifi/__init__.py" />
        <File name="__main__" src="scripts/certifi/__main__.py" />
        <File name="cacert" src="scripts/certifi/cacert.pem" />
        <File name="core" src="scripts/certifi/core.py" />
        <File name="__init__" src="scripts/cffi/__init__.py" />
        <File name="_cffi_errors" src="scripts/cffi/_cffi_errors.h" />
        <File name="_cffi_include" src="scripts/cffi/_cffi_include.h" />
        <File name="_embedding" src="scripts/cffi/_embedding.h" />
        <File name="api" src="scripts/cffi/api.py" />
        <File name="backend_ctypes" src="scripts/cffi/backend_ctypes.py" />
        <File name="cffi_opcode" src="scripts/cffi/cffi_opcode.py" />
        <File name="commontypes" src="scripts/cffi/commontypes.py" />
        <File name="cparser" src="scripts/cffi/cparser.py" />
        <File name="error" src="scripts/cffi/error.py" />
        <File name="ffiplatform" src="scripts/cffi/ffiplatform.py" />
        <File name="lock" src="scripts/cffi/lock.py" />
        <File name="model" src="scripts/cffi/model.py" />
        <File name="parse_c_type" src="scripts/cffi/parse_c_type.h" />
        <File name="recompiler" src="scripts/cffi/recompiler.py" />
        <File name="setuptools_ext" src="scripts/cffi/setuptools_ext.py" />
        <File name="vengine_cpy" src="scripts/cffi/vengine_cpy.py" />
        <File name="vengine_gen" src="scripts/cffi/vengine_gen.py" />
        <File name="verifier" src="scripts/cffi/verifier.py" />
        <File name="__about__" src="scripts/cryptography/__about__.py" />
        <File name="__init__" src="scripts/cryptography/__init__.py" />
        <File name="exceptions" src="scripts/cryptography/exceptions.py" />
        <File name="fernet" src="scripts/cryptography/fernet.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/__init__.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/backends/__init__.py" />
        <File name="interfaces" src="scripts/cryptography/hazmat/backends/interfaces.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/backends/openssl/__init__.py" />
        <File name="aead" src="scripts/cryptography/hazmat/backends/openssl/aead.py" />
        <File name="backend" src="scripts/cryptography/hazmat/backends/openssl/backend.py" />
        <File name="ciphers" src="scripts/cryptography/hazmat/backends/openssl/ciphers.py" />
        <File name="cmac" src="scripts/cryptography/hazmat/backends/openssl/cmac.py" />
        <File name="decode_asn1" src="scripts/cryptography/hazmat/backends/openssl/decode_asn1.py" />
        <File name="dh" src="scripts/cryptography/hazmat/backends/openssl/dh.py" />
        <File name="dsa" src="scripts/cryptography/hazmat/backends/openssl/dsa.py" />
        <File name="ec" src="scripts/cryptography/hazmat/backends/openssl/ec.py" />
        <File name="encode_asn1" src="scripts/cryptography/hazmat/backends/openssl/encode_asn1.py" />
        <File name="hashes" src="scripts/cryptography/hazmat/backends/openssl/hashes.py" />
        <File name="hmac" src="scripts/cryptography/hazmat/backends/openssl/hmac.py" />
        <File name="rsa" src="scripts/cryptography/hazmat/backends/openssl/rsa.py" />
        <File name="utils" src="scripts/cryptography/hazmat/backends/openssl/utils.py" />
        <File name="x25519" src="scripts/cryptography/hazmat/backends/openssl/x25519.py" />
        <File name="x509" src="scripts/cryptography/hazmat/backends/openssl/x509.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/bindings/__init__.py" />
        <File name="_constant_time" src="scripts/cryptography/hazmat/bindings/_constant_time.so" />
        <File name="_openssl" src="scripts/cryptography/hazmat/bindings/_openssl.so" />
        <File name="_padding" src="scripts/cryptography/hazmat/bindings/_padding.so" />
        <File name="__init__" src="scripts/cryptography/hazmat/bindings/openssl/__init__.py" />
        <File name="_conditional" src="scripts/cryptography/hazmat/bindings/openssl/_conditional.py" />
        <File name="binding" src="scripts/cryptography/hazmat/bindings/openssl/binding.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/primitives/__init__.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/primitives/asymmetric/__init__.py" />
        <File name="dh" src="scripts/cryptography/hazmat/primitives/asymmetric/dh.py" />
        <File name="dsa" src="scripts/cryptography/hazmat/primitives/asymmetric/dsa.py" />
        <File name="ec" src="scripts/cryptography/hazmat/primitives/asymmetric/ec.py" />
        <File name="padding" src="scripts/cryptography/hazmat/primitives/asymmetric/padding.py" />
        <File name="rsa" src="scripts/cryptography/hazmat/primitives/asymmetric/rsa.py" />
        <File name="utils" src="scripts/cryptography/hazmat/primitives/asymmetric/utils.py" />
        <File name="x25519" src="scripts/cryptography/hazmat/primitives/asymmetric/x25519.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/primitives/ciphers/__init__.py" />
        <File name="aead" src="scripts/cryptography/hazmat/primitives/ciphers/aead.py" />
        <File name="algorithms" src="scripts/cryptography/hazmat/primitives/ciphers/algorithms.py" />
        <File name="base" src="scripts/cryptography/hazmat/primitives/ciphers/base.py" />
        <File name="modes" src="scripts/cryptography/hazmat/primitives/ciphers/modes.py" />
        <File name="cmac" src="scripts/cryptography/hazmat/primitives/cmac.py" />
        <File name="constant_time" src="scripts/cryptography/hazmat/primitives/constant_time.py" />
        <File name="hashes" src="scripts/cryptography/hazmat/primitives/hashes.py" />
        <File name="hmac" src="scripts/cryptography/hazmat/primitives/hmac.py" />
        <File name="__init__" src="scripts/cryptography/hazmat/primitives/kdf/__init__.py" />
        <File name="concatkdf" src="scripts/cryptography/hazmat/primitives/kdf/concatkdf.py" />
        <File name="hkdf" src="scripts/cryptography/hazmat/primitives/kdf/hkdf.py" />
        <File name="kbkdf" src="scripts/cryptography/hazmat/primitives/kdf/kbkdf.py" />
        <File name="pbkdf2" src="scripts/cryptography/hazmat/primitives/kdf/pbkdf2.py" />
        <File name="scrypt" src="scripts/cryptography/hazmat/primitives/kdf/scrypt.py" />
        <File name="x963kdf" src="scripts/cryptography/hazmat/primitives/kdf/x963kdf.py" />
        <File name="keywrap" src="scripts/cryptography/hazmat/primitives/keywrap.py" />
        <File name="mac" src="scripts/cryptography/hazmat/primitives/mac.py" />
        <File name="padding" src="scripts/cryptography/hazmat/primitives/padding.py" />
        <File name="serialization" src="scripts/cryptography/hazmat/primitives/serialization.py" />
        <File name="serialization" src="scripts/cryptography/hazmat/primitives/serialization.pyc" />
        <File name="__init__" src="scripts/cryptography/hazmat/primitives/twofactor/__init__.py" />
        <File name="hotp" src="scripts/cryptography/hazmat/primitives/twofactor/hotp.py" />
        <File name="totp" src="scripts/cryptography/hazmat/primitives/twofactor/totp.py" />
        <File name="utils" src="scripts/cryptography/hazmat/primitives/twofactor/utils.py" />
        <File name="utils" src="scripts/cryptography/utils.py" />
        <File name="__init__" src="scripts/cryptography/x509/__init__.py" />
        <File name="base" src="scripts/cryptography/x509/base.py" />
        <File name="certificate_transparency" src="scripts/cryptography/x509/certificate_transparency.py" />
        <File name="extensions" src="scripts/cryptography/x509/extensions.py" />
        <File name="general_name" src="scripts/cryptography/x509/general_name.py" />
        <File name="name" src="scripts/cryptography/x509/name.py" />
        <File name="oid" src="scripts/cryptography/x509/oid.py" />
        <File name="LICENSE" src="scripts/enum/LICENSE" />
        <File name="README" src="scripts/enum/README" />
        <File name="__init__" src="scripts/enum/__init__.py" />
        <File name="__init__" src="scripts/idna/__init__.py" />
        <File name="codec" src="scripts/idna/codec.py" />
        <File name="compat" src="scripts/idna/compat.py" />
        <File name="core" src="scripts/idna/core.py" />
        <File name="core" src="scripts/idna/core.pyc" />
        <File name="idnadata" src="scripts/idna/idnadata.py" />
        <File name="intranges" src="scripts/idna/intranges.py" />
        <File name="package_data" src="scripts/idna/package_data.py" />
        <File name="uts46data" src="scripts/idna/uts46data.py" />
        <File name="ipaddress" src="scripts/ipaddress.py" />
        <File name="six" src="scripts/six.py" />
        <File name="translations" src="scripts/translations.ini" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
